version: '3'
services:

  middleware:
    image: devaten/mysupermon-middleware-prometheus:latest
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: mysupermon-middleware-prometheus
    depends_on: 
      - prometheus
    restart: always
    ports:
      - 8999:8999
    networks:
      - middleware

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - middleware

networks:
  middleware:
    name: middleware-network

volumes:
  prometheus-data: {}