package storage_test

import (
	"encoding/json"
	"log"
	"testing"

	"github.com/go-playground/assert/v2"
	"github.com/team7mysupermon/mySuperMon_Middleware/storage"
)

var (
	START_TEST = []byte(`{
		"status":"SUCCESS",
		"responseCode":200,
		"data":{
		   "idNum":1729,
		   "usecaseIdentifier":"MIDDELWAREAPITEST",
		   "applicationId":203,
		   "applicationName":"Konakart_Application",
		   "applicationIdentifier":"d9cdf882-6f1e-45d3-b8ca-2d1b19d9712e",
		   "dataSourceList":[
			  {
				 "dataSourceId":232,
				 "databaseType":"MySQL",
				 "databaseName":"konakart",
				 "schemaName":"konakart",
				 "hostUrl":"34.88.216.230",
				 "data":{
					"STATEMENTS":31.0,
					"STATEMENT_LATENCY_IN_S":0.02,
					"FILE_IO_LATENCY_IN_S":0.0,
					"CURRENT_CONNECTIONS":0.0,
					"DATABASE_SIZE_IN_MB":4.6,
					"STATEMENT_AVG_LATENCY_IN_MS":0.53,
					"APPLICATION_ID":203.0,
					"FILE_IOS":12.0,
					"TABLE_SCANS":7.0,
					"DATA_SOURCE_ID":232.0,
					"USECASE_IDENTIFIER":0.0,
					"UNIQUE_USERS":1.0
				 },
				 "valueObjectList":null
			  }
		   ]
		},
		"errorMessage":null,
		"errorCode":null,
		"reportLink":null
	 }`)
)

func setUpStartData() storage.StartAutoGenerated{
	var startAutoGenerated storage.StartAutoGenerated

	err := json.Unmarshal(START_TEST, &startAutoGenerated)
		if err != nil {
			log.Panicln(err)
		}

	return startAutoGenerated
}

func TestStartAutoGenerated(t *testing.T) {
	data := setUpStartData()

	assert.Equal(t, data.Status, "SUCCESS")
	assert.Equal(t, data.ResponseCode, 200)
	assert.Equal(t, data.ErrorMessage, nil)
	assert.Equal(t, data.ErrorCode, nil)
	assert.Equal(t, data.ReportLink, nil)
}

func TestStartMetaData(t *testing.T) {
	data := setUpStartData().StartMetaData

	assert.Equal(t, data.IDNum, 1682)
	assert.Equal(t, data.UsecaseIdentifier, "MIDDELWAREAPITEST")
	assert.Equal(t, data.ApplicationID, 203)
	assert.Equal(t, data.ApplicationName, "Konakart_Application")
	assert.Equal(t, data.ApplicationIdentifier, "d9cdf882-6f1e-45d3-b8ca-2d1b19d9712e")
}

func TestStartSituationResult(t *testing.T) {
	data := setUpStartData().StartMetaData.StartDataSourceList[0]

	assert.Equal(t, data.DataSourceID, 232)
	assert.Equal(t, data.DatabaseType, "MySQL")
	assert.Equal(t, data.DatabaseName, "konakart")
	assert.Equal(t, data.SchemaName, "konakart")
	assert.Equal(t, data.HostURL, "34.88.216.230")
}

func TestStartData(t *testing.T){
	data := setUpStartData().StartMetaData.StartDataSourceList[0].StartData

	assert.Equal(t, data.Statements, 31.0)
	assert.Equal(t, data.StatementLatencyInS, 0.02)
	assert.Equal(t, data.FileIoLatencyInS, 0.0)
	assert.Equal(t, data.CurrentConnections, 0.0)
	assert.Equal(t, data.DatabaseSizeInMb, 4.6)

	assert.Equal(t, data.StatementAvgLatencyInMs, 0.53)
	assert.Equal(t, data.ApplicationID, 203.0)
	assert.Equal(t, data.FileIos, 12.0)
	assert.Equal(t, data.TableScans, 7.0)
	assert.Equal(t, data.DataSourceID, 232.0)

	assert.Equal(t, data.UsecaseIdentifier, 0.0)
	assert.Equal(t, data.UniqueUsers, 1.0)
}