package storage

type StopAutoGenerated struct {
	Status       string       `json:"status"`
	ResponseCode int          `json:"responseCode"`
	StopMetaData StopMetaData `json:"data"`
	ErrorMessage interface{}  `json:"errorMessage"`
	ErrorCode    interface{}  `json:"errorCode"`
	ReportLink   string       `json:"reportLink"`
}
type StopData struct {
	Statements              float64 `json:"STATEMENTS"`
	StatementLatencyInS     float64 `json:"STATEMENT_LATENCY_IN_S"`
	FileIoLatencyInS        float64 `json:"FILE_IO_LATENCY_IN_S"`
	CurrentConnections      float64 `json:"CURRENT_CONNECTIONS"`
	DatabaseSizeInMb        float64 `json:"DATABASE_SIZE_IN_MB"`
	StatementAvgLatencyInMs float64 `json:"STATEMENT_AVG_LATENCY_IN_MS"`
	ApplicationID           float64 `json:"APPLICATION_ID"`
	FileIos                 float64 `json:"FILE_IOS"`
	TableScans              float64 `json:"TABLE_SCANS"`
	DataSourceID            float64 `json:"DATA_SOURCE_ID"`
	UsecaseIdentifier       float64 `json:"USECASE_IDENTIFIER"`
	UniqueUsers             float64 `json:"UNIQUE_USERS"`
}
type StopValueObjectList struct {
	FieldName string  `json:"fieldName"`
	NewValue  float64 `json:"newValue"`
	OldValue  float64 `json:"oldValue"`
	Deviation float64 `json:"deviation"`
}
type StopDataSourceList struct {
	DataSourceID        int                   `json:"dataSourceId"`
	DatabaseType        string                `json:"databaseType"`
	DatabaseName        string                `json:"databaseName"`
	SchemaName          interface{}           `json:"schemaName"`
	HostURL             string                `json:"hostUrl"`
	StopData            StopData              `json:"data"`
	StopValueObjectList []StopValueObjectList `json:"valueObjectList"`
}
type StopMetaData struct {
	ApplicationID         int                  `json:"applicationId"`
	ApplicationName       string               `json:"applicationName"`
	ApplicationIdentifier string               `json:"applicationIdentifier"`
	IDNum                 int                  `json:"idNum"`
	UsecaseIdentifier     string               `json:"usecaseIdentifier"`
	StartTimestamp        string               `json:"startTimestamp"`
	StopDataSourceList    []StopDataSourceList `json:"dataSourceList"`
}
