package storage

type StopAutoGenerated struct {
	Status       string      `json:"status"`
	ResponseCode int         `json:"responseCode"`
	Data         StopMetaData        `json:"data"`
	ErrorMessage interface{} `json:"errorMessage"`
	ErrorCode    interface{} `json:"errorCode"`
	ReportLink   string      `json:"reportLink"`
}
type StopData struct {
	Statements              int     `json:"STATEMENTS"`
	StatementLatencyInS     float64 `json:"STATEMENT_LATENCY_IN_S"`
	FileIoLatencyInS        int     `json:"FILE_IO_LATENCY_IN_S"`
	CurrentConnections      int     `json:"CURRENT_CONNECTIONS"`
	DatabaseSizeInMb        float64 `json:"DATABASE_SIZE_IN_MB"`
	StatementAvgLatencyInMs float64 `json:"STATEMENT_AVG_LATENCY_IN_MS"`
	ApplicationID           int     `json:"APPLICATION_ID"`
	FileIos                 int     `json:"FILE_IOS"`
	TableScans              int     `json:"TABLE_SCANS"`
	DataSourceID            int     `json:"DATA_SOURCE_ID"`
	UsecaseIdentifier       int     `json:"USECASE_IDENTIFIER"`
	UniqueUsers             int     `json:"UNIQUE_USERS"`
}
type StopValueObjectList struct {
	FieldName string `json:"fieldName"`
	NewValue  int    `json:"newValue"`
	OldValue  int    `json:"oldValue"`
	Deviation int    `json:"deviation"`
}
type StopDataSourceList struct {
	DataSourceID    int               `json:"dataSourceId"`
	DatabaseType    string            `json:"databaseType"`
	DatabaseName    string            `json:"databaseName"`
	SchemaName      interface{}       `json:"schemaName"`
	HostURL         string            `json:"hostUrl"`
	Data            StopData              `json:"data"`
	ValueObjectList []StopValueObjectList `json:"valueObjectList"`
}
type StopMetaData struct {
	ApplicationID         int              `json:"applicationId"`
	ApplicationName       string           `json:"applicationName"`
	ApplicationIdentifier string           `json:"applicationIdentifier"`
	IDNum                 int              `json:"idNum"`
	UsecaseIdentifier     string           `json:"usecaseIdentifier"`
	StartTimestamp        string           `json:"startTimestamp"`
	DataSourceList        []StopDataSourceList `json:"dataSourceList"`
}